import type { JobComment, JobPost } from './types';

const COMPANY_LOGO = '/images/logo-black.png';

const BASE_HIRING_PROCESS = [
  {
    step: 1,
    title: 'Nộp hồ sơ',
    description: 'Ứng viên điền form ứng tuyển và đính kèm CV online.',
  },
  {
    step: 2,
    title: 'Sàng lọc hồ sơ',
    description: 'Đội ngũ HR xem xét hồ sơ trong vòng 3-5 ngày làm việc.',
  },
  {
    step: 3,
    title: 'Phỏng vấn vòng 1',
    description: 'Phỏng vấn trực tuyến với HR và quản lý trực tiếp.',
  },
  {
    step: 4,
    title: 'Phỏng vấn chuyên môn',
    description: 'Bài test kỹ năng hoặc phỏng vấn chuyên sâu với team.',
  },
  {
    step: 5,
    title: 'Offer & Onboarding',
    description: 'Thông báo kết quả và hỗ trợ onboarding cho ứng viên trúng tuyển.',
  },
];

export const jobPosts: JobPost[] = [
  {
    id: 'job-1',
    slug: 'senior-frontend-developer',
    title: 'Senior Frontend Developer (React/Next.js)',
    excerpt:
      'Tham gia phát triển nền tảng AI SaaS với stack hiện đại, làm việc cùng đội ngũ kỹ sư tài năng tại TP.HCM.',
    department: 'engineering',
    location: 'TP. Hồ Chí Minh',
    jobType: 'full-time',
    level: 'senior',
    salaryMin: 35000000,
    salaryMax: 55000000,
    salaryCurrency: 'VND',
    experience: '3-5 năm',
    headcount: 2,
    publishedAt: '2025-06-01T08:00:00Z',
    deadline: '2025-07-15T23:59:59Z',
    views: 2840,
    likes: 156,
    featured: true,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&h=500&fit=crop',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'GraphQL'],
    description:
      'Chúng tôi đang tìm kiếm Senior Frontend Developer có kinh nghiệm để tham gia xây dựng giao diện người dùng cho nền tảng AI SaaS. Bạn sẽ làm việc trực tiếp với team Product và Design để tạo ra trải nghiệm người dùng xuất sắc.',
    responsibilities: [
      'Phát triển và duy trì các tính năng frontend với React/Next.js',
      'Tối ưu hiệu năng, SEO và Core Web Vitals',
      'Review code và mentor các developer junior',
      'Phối hợp với team Design để implement UI/UX',
      'Tham gia thiết kế kiến trúc frontend và chọn công nghệ',
    ],
    requirements: [
      'Tối thiểu 3 năm kinh nghiệm phát triển frontend',
      'Thành thạo React, Next.js và TypeScript',
      'Kinh nghiệm với Tailwind CSS và responsive design',
      'Hiểu biết về SSR, SSG và SEO optimization',
      'Kỹ năng giao tiếp tốt, làm việc nhóm hiệu quả',
    ],
    benefits: [
      'Lương thưởng cạnh tranh + ESOP',
      'Bảo hiểm sức khỏe cao cấp cho bản thân và gia đình',
      'Làm việc linh hoạt 2 ngày/tuần tại văn phòng',
      'Ngân sách học tập 10 triệu/năm',
      'Team building hàng quý',
      'MacBook Pro và thiết bị làm việc cao cấp',
    ],
    salaryDetails:
      'Mức lương từ 35-55 triệu VND/tháng tùy kinh nghiệm. Thưởng performance 2 lần/năm. Review lương 2 lần/năm.',
    workSchedule: 'Thứ 2 - Thứ 6, 9:00 - 18:00 (linh hoạt 1 giờ)',
    workLocation: 'Tầng 12, Tòa nhà Bitexco, Quận 1, TP.HCM',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'AIStarterKit là startup công nghệ AI hàng đầu Việt Nam, cung cấp nền tảng SaaS giúp doanh nghiệp tích hợp AI vào quy trình làm việc. Với hơn 50 nhân viên và 10.000+ khách hàng, chúng tôi đang mở rộng mạnh mẽ.',
  },
  {
    id: 'job-2',
    slug: 'ai-engineer',
    title: 'AI/ML Engineer',
    excerpt:
      'Xây dựng và triển khai các mô hình AI cho sản phẩm chatbot và text generation.',
    department: 'engineering',
    location: 'Hà Nội',
    jobType: 'full-time',
    level: 'mid',
    salaryMin: 30000000,
    salaryMax: 45000000,
    salaryCurrency: 'VND',
    experience: '2-4 năm',
    headcount: 1,
    publishedAt: '2025-06-05T08:00:00Z',
    deadline: '2025-07-20T23:59:59Z',
    views: 1920,
    likes: 98,
    featured: true,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=500&fit=crop',
    skills: ['Python', 'AI/ML', 'PyTorch', 'LangChain', 'Node.js'],
    description:
      'Vị trí AI/ML Engineer yêu cầu bạn thiết kế, huấn luyện và triển khai các mô hình AI cho sản phẩm của chúng tôi, bao gồm chatbot thông minh và công cụ tạo nội dung AI.',
    responsibilities: [
      'Phát triển và fine-tune các mô hình LLM cho use case cụ thể',
      'Xây dựng pipeline xử lý dữ liệu và RAG system',
      'Tối ưu hiệu năng inference và chi phí API',
      'Nghiên cứu và áp dụng các kỹ thuật AI mới nhất',
      'Viết tài liệu kỹ thuật và hướng dẫn sử dụng',
    ],
    requirements: [
      '2+ năm kinh nghiệm với Machine Learning / Deep Learning',
      'Thành thạo Python, PyTorch hoặc TensorFlow',
      'Kinh nghiệm với LLM, prompt engineering, RAG',
      'Hiểu biết về MLOps và model deployment',
      'Tiếng Anh đọc hiểu tài liệu kỹ thuật tốt',
    ],
    benefits: [
      'Lương cạnh tranh + thưởng dự án AI',
      'Làm việc với GPU cluster hiện đại',
      'Tham dự conference AI quốc tế',
      'Remote 3 ngày/tuần',
      'Bảo hiểm full package',
    ],
    salaryDetails: '30-45 triệu VND/tháng. Thưởng theo milestone dự án AI.',
    workSchedule: 'Thứ 2 - Thứ 6, linh hoạt giờ làm việc',
    workLocation: 'Tầng 8, Tòa nhà Keangnam, Cầu Giấy, Hà Nội',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'AIStarterKit đầu tư mạnh vào R&D AI với team 15+ kỹ sư AI. Sản phẩm được sử dụng bởi hàng nghìn doanh nghiệp tại Việt Nam và khu vực.',
  },
  {
    id: 'job-3',
    slug: 'product-manager',
    title: 'Product Manager',
    excerpt:
      'Dẫn dắt chiến lược sản phẩm AI SaaS, làm việc chặt chẽ với Engineering và Design.',
    department: 'product',
    location: 'TP. Hồ Chí Minh',
    jobType: 'full-time',
    level: 'senior',
    salaryMin: 40000000,
    salaryMax: 60000000,
    salaryCurrency: 'VND',
    experience: '4-6 năm',
    headcount: 1,
    publishedAt: '2025-06-08T08:00:00Z',
    deadline: '2025-07-25T23:59:59Z',
    views: 1560,
    likes: 87,
    featured: true,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=500&fit=crop',
    skills: ['Product Management', 'Agile', 'Data Analysis', 'User Research'],
    description:
      'Product Manager sẽ chịu trách nhiệm định hướng roadmap sản phẩm, ưu tiên tính năng và đảm bảo sản phẩm đáp ứng nhu cầu khách hàng doanh nghiệp.',
    responsibilities: [
      'Xây dựng và quản lý product roadmap',
      'Phân tích dữ liệu người dùng và đề xuất cải tiến',
      'Viết PRD, user stories và acceptance criteria',
      'Phối hợp cross-functional với Engineering, Design, Marketing',
      'Theo dõi KPIs và báo cáo tiến độ cho leadership',
    ],
    requirements: [
      '4+ năm kinh nghiệm Product Management trong SaaS/B2B',
      'Kinh nghiệm với sản phẩm AI hoặc công nghệ là lợi thế',
      'Kỹ năng phân tích dữ liệu và ra quyết định dựa trên data',
      'Khả năng giao tiếp và thuyết trình xuất sắc',
      'Tiếng Anh giao tiếp tốt',
    ],
    benefits: [
      'Lương senior PM + ESOP',
      'Quyền quyết định cao về product direction',
      'Ngân sách user research không giới hạn',
      'Hybrid work model',
      'Health insurance premium',
    ],
    salaryDetails: '40-60 triệu VND/tháng. Bonus theo OKR quý.',
    workSchedule: 'Thứ 2 - Thứ 6, 9:00 - 18:00',
    workLocation: 'Tầng 12, Tòa nhà Bitexco, Quận 1, TP.HCM',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'AIStarterKit có product team 8 người, phục vụ 10.000+ khách hàng B2B với NPS 72. Chúng tôi đang scale product lên enterprise tier.',
  },
  {
    id: 'job-4',
    slug: 'ui-ux-designer',
    title: 'UI/UX Designer',
    excerpt:
      'Thiết kế trải nghiệm người dùng cho nền tảng AI, từ wireframe đến high-fidelity prototype.',
    department: 'design',
    location: 'Đà Nẵng',
    jobType: 'full-time',
    level: 'mid',
    salaryMin: 18000000,
    salaryMax: 28000000,
    salaryCurrency: 'VND',
    experience: '2-3 năm',
    headcount: 1,
    publishedAt: '2025-06-10T08:00:00Z',
    deadline: '2025-07-30T23:59:59Z',
    views: 980,
    likes: 64,
    featured: false,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=500&fit=crop',
    skills: ['Figma', 'UI Design', 'UX Research', 'Design System'],
    description:
      'UI/UX Designer sẽ thiết kế giao diện và trải nghiệm người dùng cho các sản phẩm AI của công ty, đảm bảo tính nhất quán và dễ sử dụng.',
    responsibilities: [
      'Thiết kế UI/UX cho web app và mobile responsive',
      'Xây dựng và duy trì Design System',
      'Conduct user research và usability testing',
      'Tạo wireframe, prototype và handoff cho developers',
      'Collaborate với PM và Engineering team',
    ],
    requirements: [
      '2+ năm kinh nghiệm UI/UX design',
      'Portfolio thể hiện quy trình design rõ ràng',
      'Thành thạo Figma và prototyping tools',
      'Hiểu biết về accessibility và responsive design',
      'Kinh nghiệm thiết kế SaaS/dashboard là lợi thế',
    ],
    benefits: [
      'Lương cạnh tranh khu vực Đà Nẵng',
      'Remote full-time',
      'Figma Professional license',
      'Khóa học design online',
      'Flexible working hours',
    ],
    salaryDetails: '18-28 triệu VND/tháng. Review lương 2 lần/năm.',
    workSchedule: 'Linh hoạt, deliverable-based',
    workLocation: 'Remote - Đà Nẵng',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'AIStarterKit có design team distributed, làm việc async với các team tại HCM và Hà Nội.',
  },
  {
    id: 'job-5',
    slug: 'marketing-specialist',
    title: 'Digital Marketing Specialist',
    excerpt:
      'Lên chiến lược và thực thi các chiến dịch marketing digital cho sản phẩm AI SaaS.',
    department: 'marketing',
    location: 'TP. Hồ Chí Minh',
    jobType: 'full-time',
    level: 'mid',
    salaryMin: 15000000,
    salaryMax: 25000000,
    salaryCurrency: 'VND',
    experience: '2-3 năm',
    headcount: 2,
    publishedAt: '2025-06-12T08:00:00Z',
    deadline: '2025-08-01T23:59:59Z',
    views: 720,
    likes: 42,
    featured: false,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=500&fit=crop',
    skills: ['SEO', 'Google Ads', 'Content Marketing', 'Analytics'],
    description:
      'Digital Marketing Specialist chịu trách nhiệm tăng trưởng user acquisition và brand awareness cho nền tảng AIStarterKit thông qua các kênh digital.',
    responsibilities: [
      'Lập kế hoạch và thực hiện chiến dịch SEO, SEM',
      'Quản lý social media và content calendar',
      'Phân tích metrics và tối ưu conversion funnel',
      'Collaborate với Content team cho blog và case study',
      'A/B testing landing pages và ad creatives',
    ],
    requirements: [
      '2+ năm kinh nghiệm digital marketing B2B/SaaS',
      'Kinh nghiệm với Google Ads, Meta Ads, SEO tools',
      'Khả năng phân tích data với GA4, Mixpanel',
      'Kỹ năng viết content tiếng Việt tốt',
      'Creative mindset và data-driven approach',
    ],
    benefits: [
      'Lương + KPI bonus hấp dẫn',
      'Ngân sách ads để thực hành',
      'Khóa học marketing certification',
      'Team outing hàng tháng',
      'Hybrid work',
    ],
    salaryDetails: '15-25 triệu VND/tháng + bonus KPI 20%/quý.',
    workSchedule: 'Thứ 2 - Thứ 6, 9:00 - 18:00',
    workLocation: 'Tầng 12, Tòa nhà Bitexco, Quận 1, TP.HCM',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'Marketing team 6 người, quản lý ngân sách 500M+/năm cho growth marketing.',
  },
  {
    id: 'job-6',
    slug: 'frontend-intern',
    title: 'Frontend Developer Intern',
    excerpt:
      'Cơ hội thực tập cho sinh viên IT muốn học React/Next.js trong môi trường startup AI.',
    department: 'engineering',
    location: 'TP. Hồ Chí Minh',
    jobType: 'intern',
    level: 'junior',
    salaryMin: 5000000,
    salaryMax: 8000000,
    salaryCurrency: 'VND',
    experience: 'Sinh viên năm 3-4',
    headcount: 3,
    publishedAt: '2025-06-14T08:00:00Z',
    deadline: '2025-08-15T23:59:59Z',
    views: 3200,
    likes: 210,
    featured: true,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&h=500&fit=crop',
    skills: ['React', 'JavaScript', 'HTML/CSS', 'Git'],
    description:
      'Chương trình thực tập Frontend Developer dành cho sinh viên năm cuối ngành CNTT, cung cấp kinh nghiệm thực tế với dự án production.',
    responsibilities: [
      'Hỗ trợ phát triển UI components với React',
      'Fix bugs và viết unit tests',
      'Tham gia code review và học best practices',
      'Research công nghệ mới và present cho team',
      'Document code và viết technical notes',
    ],
    requirements: [
      'Sinh viên năm 3-4 ngành CNTT hoặc tương đương',
      'Biết HTML, CSS, JavaScript cơ bản',
      'Đã học hoặc tự học React',
      'Có project cá nhân trên GitHub là lợi thế',
      'Tinh thần học hỏi cao, làm việc nhóm tốt',
    ],
    benefits: [
      'Phụ cấp thực tập 5-8 triệu/tháng',
      'Mentor 1-1 từ Senior Developer',
      'Cơ hội full-time sau thực tập',
      'Certificate và recommendation letter',
      'Snacks và team activities',
    ],
    salaryDetails: 'Phụ cấp 5-8 triệu VND/tháng. Thực tập 3-6 tháng.',
    workSchedule: 'Thứ 2 - Thứ 6, 9:00 - 18:00 (tối thiểu 30h/tuần)',
    workLocation: 'Tầng 12, Tòa nhà Bitexco, Quận 1, TP.HCM',
    hiringProcess: BASE_HIRING_PROCESS.slice(0, 4),
    companyInfo:
      'AIStarterKit đã đào tạo 20+ intern, 80% chuyển sang full-time. Môi trường học hỏi nhanh, thực chiến.',
  },
  {
    id: 'job-7',
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    excerpt:
      'Xây dựng và vận hành hạ tầng cloud cho nền tảng AI với AWS/Kubernetes.',
    department: 'engineering',
    location: 'Remote',
    jobType: 'remote',
    level: 'senior',
    salaryMin: 35000000,
    salaryMax: 50000000,
    salaryCurrency: 'VND',
    experience: '3-5 năm',
    headcount: 1,
    publishedAt: '2025-06-15T08:00:00Z',
    deadline: '2025-08-10T23:59:59Z',
    views: 890,
    likes: 53,
    featured: false,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1667372393119-3d21c2d1e8f0?w=1200&h=500&fit=crop',
    skills: ['DevOps', 'AWS', 'Kubernetes', 'Docker', 'CI/CD'],
    description:
      'DevOps Engineer sẽ thiết kế, triển khai và duy trì hạ tầng cloud scalable cho platform AI, đảm bảo uptime 99.9%.',
    responsibilities: [
      'Quản lý infrastructure trên AWS (EKS, RDS, S3)',
      'Xây dựng CI/CD pipelines với GitHub Actions',
      'Monitor và alert với Datadog/Prometheus',
      'Implement security best practices và compliance',
      'Automate deployment và scaling',
    ],
    requirements: [
      '3+ năm kinh nghiệm DevOps/SRE',
      'Thành thạo AWS, Docker, Kubernetes',
      'Kinh nghiệm với Terraform hoặc CloudFormation',
      'Hiểu biết về networking và security',
      'Scripting với Python hoặc Bash',
    ],
    benefits: [
      'Remote 100%, flexible timezone',
      'Lương USD-equivalent competitive',
      'Home office setup budget 15 triệu',
      'Conference và certification budget',
      'Async-first culture',
    ],
    salaryDetails: '35-50 triệu VND/tháng. Thanh toán qua bank transfer.',
    workSchedule: 'Flexible, overlap 4h với team HCM (9-13 ICT)',
    workLocation: 'Remote - Việt Nam',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'Infrastructure team 4 người, xử lý 1M+ API requests/day với latency p99 < 200ms.',
  },
  {
    id: 'job-8',
    slug: 'sales-executive',
    title: 'Sales Executive (B2B SaaS)',
    excerpt:
      'Phát triển khách hàng doanh nghiệp cho giải pháp AI SaaS tại thị trường Việt Nam.',
    department: 'sales',
    location: 'Hà Nội',
    jobType: 'full-time',
    level: 'mid',
    salaryMin: 15000000,
    salaryMax: 20000000,
    salaryCurrency: 'VND',
    experience: '2-3 năm',
    headcount: 2,
    publishedAt: '2025-06-16T08:00:00Z',
    deadline: '2025-08-20T23:59:59Z',
    views: 450,
    likes: 28,
    featured: false,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&h=500&fit=crop',
    skills: ['B2B Sales', 'CRM', 'Negotiation', 'SaaS'],
    description:
      'Sales Executive chịu trách nhiệm tìm kiếm, nurture và close deals với khách hàng doanh nghiệp sử dụng giải pháp AI của chúng tôi.',
    responsibilities: [
      'Prospect và qualify leads từ marketing',
      'Demo sản phẩm và present value proposition',
      'Negotiate contract và close deals',
      'Maintain CRM pipeline chính xác',
      'Collaborate với CS team cho onboarding',
    ],
    requirements: [
      '2+ năm kinh nghiệm B2B sales, ưu tiên SaaS/Tech',
      'Track record đạt/quá quota',
      'Kỹ năng presentation và negotiation',
      'Sử dụng CRM (HubSpot/Salesforce)',
      'Tiếng Anh giao tiếp cơ bản',
    ],
    benefits: [
      'Lương cứng + commission không giới hạn',
      'OTE 40-60 triệu/tháng cho top performer',
      'Company car allowance',
      'Sales kickoff trip hàng năm',
      'Fast promotion path',
    ],
    salaryDetails: 'Lương cứng 15-20 triệu + commission 10-30% deal value.',
    workSchedule: 'Thứ 2 - Thứ 6, linh hoạt theo lịch khách hàng',
    workLocation: 'Tầng 8, Tòa nhà Keangnam, Cầu Giấy, Hà Nội',
    hiringProcess: BASE_HIRING_PROCESS,
    companyInfo:
      'Sales team 10 AE, average deal size 50M VND, sales cycle 30-60 ngày.',
  },
  {
    id: 'job-9',
    slug: 'hr-specialist',
    title: 'HR Specialist',
    excerpt:
      'Hỗ trợ tuyển dụng, onboarding và phát triển văn hóa doanh nghiệp tại startup AI.',
    department: 'hr',
    location: 'TP. Hồ Chí Minh',
    jobType: 'part-time',
    level: 'mid',
    salaryMin: 10000000,
    salaryMax: 15000000,
    salaryCurrency: 'VND',
    experience: '2-3 năm',
    headcount: 1,
    publishedAt: '2025-06-17T08:00:00Z',
    deadline: '2025-08-25T23:59:59Z',
    views: 380,
    likes: 19,
    featured: false,
    companyLogo: COMPANY_LOGO,
    coverImage:
      'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&h=500&fit=crop',
    skills: ['Recruitment', 'HR Management', 'Employer Branding'],
    description:
      'HR Specialist hỗ trợ toàn bộ quy trình nhân sự từ tuyển dụng, onboarding đến employee engagement trong giai đoạn scale-up.',
    responsibilities: [
      'Quản lý full-cycle recruitment',
      'Onboarding và offboarding nhân viên mới',
      'Xây dựng employer branding trên các kênh',
      'Hỗ trợ payroll và benefits administration',
      'Organize team events và engagement activities',
    ],
    requirements: [
      '2+ năm kinh nghiệm HR, ưu tiên tech startup',
      'Kinh nghiệm tuyển dụng IT/Tech roles',
      'Kỹ năng giao tiếp và organization',
      'Sử dụng ATS và HR tools',
      'Passion về văn hóa startup',
    ],
    benefits: [
      'Part-time linh hoạt 20-30h/tuần',
      'Remote 2 ngày/tuần',
      'Cơ hội chuyển full-time',
      'Làm việc với leadership trực tiếp',
      'HR certification support',
    ],
    salaryDetails: '10-15 triệu VND/tháng (part-time). Pro-rate theo giờ.',
    workSchedule: 'Thứ 2 - Thứ 6, 4-6h/ngày linh hoạt',
    workLocation: 'Tầng 12, Tòa nhà Bitexco, Quận 1, TP.HCM',
    hiringProcess: BASE_HIRING_PROCESS.slice(0, 3),
    companyInfo:
      'Team 50 người, đang tuyển thêm 20 headcount trong 2025. Culture: transparent, growth-minded.',
  },
];

export const jobComments: JobComment[] = [
  {
    id: 'jc-1',
    jobId: 'job-1',
    author: {
      name: 'Nguyễn Văn A',
      avatar: 'https://avatars.githubusercontent.com/u/5?v=4',
    },
    content:
      'Vị trí này có yêu cầu remote không ạ? Mình đang ở Đà Nẵng nhưng có thể relocate.',
    createdAt: '2025-06-10T10:30:00Z',
    likes: 5,
    replies: [
      {
        id: 'jc-1-r1',
        jobId: 'job-1',
        author: {
          name: 'HR AIStarterKit',
          avatar: 'https://avatars.githubusercontent.com/u/1?v=4',
        },
        content:
          'Chào bạn! Vị trí này hybrid 2 ngày/tuần tại văn phòng HCM. Remote full chỉ áp dụng cho vị trí DevOps và Design.',
        createdAt: '2025-06-10T14:00:00Z',
        likes: 3,
      },
    ],
  },
  {
    id: 'jc-2',
    jobId: 'job-1',
    author: {
      name: 'Trần Thị B',
      avatar: 'https://avatars.githubusercontent.com/u/6?v=4',
    },
    content:
      'Mình đã ứng tuyển tuần trước, chưa nhận được phản hồi. Thường mất bao lâu để HR liên hệ?',
    createdAt: '2025-06-12T09:15:00Z',
    likes: 2,
    isOwner: true,
  },
  {
    id: 'jc-3',
    jobId: 'job-6',
    author: {
      name: 'Lê Minh C',
      avatar: 'https://avatars.githubusercontent.com/u/7?v=4',
    },
    content:
      'Sinh viên năm 2 có được apply thực tập không ạ? Mình đã có project React trên GitHub.',
    createdAt: '2025-06-15T16:45:00Z',
    likes: 8,
  },
];
