/**
 * Random Data Seeder for VN168 (Next.js + Drizzle + PostgreSQL)
 * 
 * Follows random-data-seeder skill guidelines:
 * - Idempotent (safe to run multiple times)
 * - Vietnamese localized data
 * - Uses @faker-js/faker + curated pools (like RandomData_DB spirit)
 * - Proper seeding order for relations
 * - Media handled via stable image URLs
 * - Reproducible via seed
 *
 * Usage:
 *   npx tsx scripts/seed.ts
 *   # or
 *   npm run db:seed
 */

import { faker } from '@faker-js/faker/locale/vi';
import { db } from '../src/db';
import {
  users,
  categories,
  articles,
  comments,
  orders,
  banners,
  jobs,
  invoices,
} from '../src/db/schema';
import {
  VN_SURNAMES,
  ARTICLE_CATEGORIES,
  ARTICLE_TITLES,
  PACKAGES,
  generateVietnameseName,
  generateEmail,
  generatePhone,
  generateImageUrl,
  generateOrderAmount,
  pickRandom,
  ORDER_STATUSES,
  USER_STATUSES,
  ARTICLE_STATUSES,
  AI_TOOLS_LIST,
  PAYMENT_METHODS,
  generateInvoiceAmount,
  generateApiKeyName,
  generateDuration,
  generateRevenueReport,
  generatePerformanceReport,
  generateTrafficReport,
  generateUsersReport,
} from '../src/lib/seed/generators';
import { count } from 'drizzle-orm';
import fs from 'fs';
import path from 'path';

// ======================
// ENV CONFIG FOR SEEDER
// ======================
const isDevelopment = process.env.NODE_ENV !== 'production';
const SEED_TO_DB = process.env.SEED_TO_DB !== 'false';           // default: seed DB
const SEED_TO_JSON = process.env.SEED_TO_JSON === 'true' ||     // explicit
  (isDevelopment && process.env.SEED_TO_JSON !== 'false');      // auto in local/dev unless disabled

console.log(`🔧 Seeder config: NODE_ENV=${process.env.NODE_ENV || 'undefined'} | SEED_TO_DB=${SEED_TO_DB} | SEED_TO_JSON=${SEED_TO_JSON}`);

// Make runs reproducible
faker.seed(20260630);

const NUM_USERS = 28;
const NUM_ARTICLES = 42;
const NUM_COMMENTS = 65;
const NUM_ORDERS = 35;
const NUM_BANNERS = 5;
const NUM_JOBS = 7;

// ======================
// JSON OUTPUT HELPERS
// ======================

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function writeSeedJson(data: Record<string, any[] | Record<string, any>>) {
  // 1. Private seed-data (for server / gitignored)
  const privateDir = path.join(process.cwd(), 'seed-data');
  ensureDir(privateDir);

  // 2. Public seed-data (so client can fetch /seed-data/xxx.json in local dev)
  const publicDir = path.join(process.cwd(), 'public', 'seed-data');
  ensureDir(publicDir);

  Object.entries(data).forEach(([name, records]) => {
    const json = JSON.stringify(records, null, 2);
    const count = Array.isArray(records) ? records.length : (records && typeof records === 'object' ? Object.keys(records).length : 1);

    // Write to private
    const privatePath = path.join(privateDir, `${name}.json`);
    fs.writeFileSync(privatePath, json, 'utf-8');
    console.log(`  📄 Written ${count} item(s) → ${privatePath}`);

    // Also write to public/ for client-side fetch (very useful for local)
    const publicPath = path.join(publicDir, `${name}.json`);
    fs.writeFileSync(publicPath, json, 'utf-8');
  });

  // Write manifest in both places
  const manifest = {
    generatedAt: new Date().toISOString(),
    counts: Object.fromEntries(Object.entries(data).map(([k, v]) => [k, v.length])),
    note: 'Generated by scripts/seed.ts when SEED_TO_JSON=true (or auto in development). Use these instead of static mocks in local.',
  };
  const manifestJson = JSON.stringify(manifest, null, 2);

  fs.writeFileSync(path.join(privateDir, 'seed-manifest.json'), manifestJson, 'utf-8');
  fs.writeFileSync(path.join(publicDir, 'seed-manifest.json'), manifestJson, 'utf-8');

  console.log(`  📄 Written manifests to seed-data/ and public/seed-data/`);
}

// ======================
// PURE GENERATORS (for JSON output + reusable)
// ======================

function generateCategoriesData() {
  return ARTICLE_CATEGORIES.map((cat, idx) => ({
    id: idx + 1,
    name: cat.name,
    slug: cat.slug,
    parent: idx > 3 && Math.random() > 0.7 ? pickRandom(ARTICLE_CATEGORIES.slice(0, 4)).name : null,
    status: Math.random() > 0.85 ? 'inactive' : 'active',
    createdAt: new Date().toISOString(),
  }));
}

function generateUsersData() {
  const data = Array.from({ length: NUM_USERS }).map((_, index) => {
    const name = generateVietnameseName();
    const rolePool = ['User', 'User', 'User', 'Pro', 'Pro', 'Admin'];
    const role = pickRandom(rolePool);
    const status = pickRandom([...USER_STATUSES]);

    return {
      id: index + 1,
      name,
      email: generateEmail(name),
      avatar: generateImageUrl(`user-${name}`, 128, 128),
      role,
      status,
      createdAt: faker.date.past({ years: 1.5 }).toISOString(),
    };
  });

  // Pin demo users (same as DB seed)
  data[0].name = 'Nguyễn Thị Lan';
  data[0].email = 'lan.nguyen@vn168.vn';
  data[0].role = 'Admin';
  data[0].status = 'active';

  data[1].name = 'Trần Văn Minh';
  data[1].email = 'minh.tran@vn168.vn';
  data[1].role = 'Pro';
  data[1].status = 'active';

  return data;
}

function generateArticlesData(cats: any[]) {
  const authors = ['Admin AIStarterKit', 'Nguyễn Thị Lan', 'Trần Văn Minh', 'Phạm Thu Hà', 'Lê Hoàng An'];

  return Array.from({ length: NUM_ARTICLES }).map((_, i) => {
    const cat = pickRandom(cats);
    const title = i < ARTICLE_TITLES.length ? ARTICLE_TITLES[i] : faker.lorem.sentence({ min: 8, max: 14 });
    const slugBase = title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 80);
    const slug = `${slugBase}-${1000 + i}`;

    const status = pickRandom([...ARTICLE_STATUSES]);
    const views = faker.number.int({ min: 80, max: 12400 });
    const featured = Math.random() > 0.75;

    return {
      id: i + 1,
      title,
      slug,
      excerpt: pickRandom([
        'Khám phá cách tận dụng AI để tăng năng suất làm việc và sáng tạo nội dung chuyên nghiệp.',
        'Các chiến lược thực tế giúp sử dụng AI hiệu quả trong quy trình làm việc hàng ngày.',
        faker.lorem.paragraph({ min: 1, max: 2 }).slice(0, 180),
      ]),
      content: `<p>${faker.lorem.paragraphs(4, '<br/><br/>')}</p>`,
      categoryId: cat.id,
      categorySlug: cat.slug,
      author: pickRandom(authors),
      status,
      views,
      likes: faker.number.int({ min: 5, max: 420 }),
      readTime: faker.number.int({ min: 4, max: 14 }),
      featured,
      coverImage: generateImageUrl(`article-${slugBase}`, 1200, 630),
      publishedAt: status === 'published' ? faker.date.recent({ days: 90 }).toISOString() : null,
      createdAt: faker.date.past({ years: 1 }).toISOString(),
    };
  });
}

function generateCommentsData(arts: any[]) {
  const data: any[] = [];

  for (let i = 0; i < NUM_COMMENTS; i++) {
    const article = pickRandom(arts);
    const name = generateVietnameseName();
    const statuses = ['approved', 'approved', 'approved', 'pending', 'hidden', 'reported'];

    data.push({
      id: i + 1,
      articleId: article.id,
      articleSlug: article.slug,
      authorName: name,
      authorAvatar: generateImageUrl(`comment-${name}`, 64, 64),
      content: faker.lorem.sentence({ min: 6, max: 18 }),
      status: pickRandom(statuses),
      likes: faker.number.int({ min: 0, max: 28 }),
      createdAt: faker.date.recent({ days: 45 }).toISOString(),
    });
  }

  return data;
}

function generateOrdersData() {
  return Array.from({ length: NUM_ORDERS }).map((_, i) => {
    const pkg = pickRandom(PACKAGES);
    const name = generateVietnameseName();
    const email = generateEmail(name);
    const status = pickRandom([...ORDER_STATUSES]);

    return {
      id: i + 1,
      orderNumber: `ORD-${2800 + i}`,
      customerName: name,
      customerEmail: email,
      packageName: pkg.name,
      amount: generateOrderAmount(pkg.price),
      status,
      createdAt: faker.date.recent({ days: 120 }).toISOString(),
    };
  });
}

function generateBannersData() {
  const positions = [
    'Trang chủ - Hero',
    'Sidebar',
    'Trang Pricing',
    'Trang Blog',
    'Dashboard Header',
  ];

  const now = new Date();

  return Array.from({ length: NUM_BANNERS }).map((_, i) => {
    const status: 'active' | 'inactive' | 'scheduled' =
      i === 0 ? 'active' : (Math.random() > 0.3 ? 'active' : 'scheduled');

    // Safe date range (avoid "from must be before to")
    const start = faker.date.between({ from: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 90), to: now });
    const end = faker.date.between({ from: now, to: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 200) });

    return {
      id: i + 1,
      title: pickRandom([
        'Hero Banner - Ưu đãi mùa hè',
        'Sidebar Promo AI Pro',
        'Pricing Campaign Q3',
        'Blog Feature - AI mới',
        'Khám phá công cụ mới',
      ]),
      position: positions[i] || positions[0],
      image: generateImageUrl(`banner-${i}`, 1400, 600),
      status,
      startDate: start.toISOString(),
      endDate: end.toISOString(),
      createdAt: now.toISOString(),
    };
  });
}

function generateJobsData() {
  return Array.from({ length: NUM_JOBS }).map((_, i) => {
    const title = i < 4 ? pickRandom([
      'Senior Frontend Developer (React/Next.js)',
      'AI/ML Engineer',
      'Product Designer (AI SaaS)',
      'Backend Engineer - Platform',
    ]) : faker.person.jobTitle() + ' (AI)';

    const slug = title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-');

    const dept = pickRandom(['engineering', 'product', 'marketing', 'design', 'hr'] as const);

    return {
      id: i + 1,
      slug: `${slug}-${900 + i}`,
      title,
      excerpt: 'Tham gia phát triển nền tảng AI SaaS với stack hiện đại tại TP.HCM.',
      department: dept,
      location: pickRandom(['TP. Hồ Chí Minh', 'Hà Nội', 'Remote', 'Hybrid - TP.HCM']),
      jobType: pickRandom(['full-time', 'part-time', 'remote'] as const),
      level: pickRandom(['junior', 'mid', 'senior', 'lead'] as const),
      salaryMin: 22000000,
      salaryMax: 62000000,
      salaryCurrency: 'VND',
      experience: pickRandom(['1-2 năm', '2-3 năm', '3-5 năm', '5+ năm']),
      headcount: pickRandom([1, 2, 3]),
      publishedAt: faker.date.recent({ days: 60 }).toISOString(),
      deadline: faker.date.between({ from: new Date(), to: new Date(Date.now() + 1000 * 60 * 60 * 24 * 120) }).toISOString(),
      views: faker.number.int({ min: 240, max: 5200 }),
      likes: faker.number.int({ min: 12, max: 180 }),
      featured: i === 0,
      companyLogo: '/images/black.png',
      coverImage: generateImageUrl(`job-${slug}`, 1200, 500),
      skills: ['TypeScript', 'React', 'Next.js', 'AI', 'Tailwind'],
      description: 'Chúng tôi đang tìm kiếm thành viên tài năng để xây dựng các sản phẩm AI chất lượng cao.',
      responsibilities: ['Xây dựng tính năng mới', 'Review code', 'Hợp tác với team design'],
      requirements: ['Kinh nghiệm 3+ năm', 'Thành thạo React/TS', 'Tư duy sản phẩm tốt'],
      benefits: ['Lương thưởng cạnh tranh', 'BHYT cao cấp', 'Làm việc linh hoạt'],
      createdAt: new Date().toISOString(),
    };
  });
}

function generateCustomersData(users: any[]) {
  return users.slice(0, 12).map((u, i) => ({
    id: String(i + 1),
    name: u.name,
    email: u.email,
    phone: generatePhone(),
    package: pickRandom(['Starter', 'Pro', 'Enterprise']),
    totalSpent: Math.floor(Math.random() * 5000000) + 199000,
    status: u.status === 'locked' ? 'inactive' : 'active',
    joinedAt: u.createdAt,
  }));
}

function generateInvoicesData() {
  return Array.from({ length: 18 }).map((_, i) => {
    const statusPool: Array<'paid' | 'pending' | 'overdue'> = ['paid', 'paid', 'paid', 'pending', 'overdue'];
    return {
      id: `INV-${String(100 + i).padStart(3, '0')}`,
      customer: generateVietnameseName(),
      amount: generateInvoiceAmount(),
      status: pickRandom(statusPool),
      date: faker.date.recent({ days: 40 }).toISOString().split('T')[0],
    };
  });
}

function generateApiKeysData() {
  return Array.from({ length: 6 }).map((_, i) => ({
    id: String(i + 1),
    name: generateApiKeyName(),
    key: `sk-****...${faker.string.alphanumeric(6)}`,
    status: i === 5 ? 'revoked' : 'active',
    createdAt: faker.date.past({ years: 0.5 }).toISOString().split('T')[0],
    lastUsed: faker.date.recent({ days: 2 }).toISOString().split('T')[0],
  }));
}

function generateAiToolsData() {
  return AI_TOOLS_LIST.map((tool, i) => ({
    id: String(i + 1),
    name: tool.name,
    type: tool.type,
    status: i === 3 ? 'inactive' : 'active',
    usage: faker.number.int({ min: 400, max: 9500 }),
    tokens: `${(Math.random() * 3 + 0.3).toFixed(1)}M`,
  }));
}

function generateAiHistoryData(users: any[]) {
  return Array.from({ length: 25 }).map((_, i) => {
    const tool = pickRandom(AI_TOOLS_LIST);
    const user = pickRandom(users);
    return {
      id: String(i + 1),
      user: user.name,
      tool: tool.name,
      tokens: faker.number.int({ min: 200, max: 4500 }),
      duration: generateDuration(),
      createdAt: faker.date.recent({ days: 7 }).toISOString().replace('T', ' ').substring(0, 16),
    };
  });
}

function generateReportData() {
  return {
    revenue: generateRevenueReport(),
    performance: generatePerformanceReport(),
    traffic: generateTrafficReport(),
    users: generateUsersReport(),
  };
}

function generateNotificationsData() {
  return [
    { id: '1', title: 'Đơn hàng mới', message: 'ORD-2847 vừa được thanh toán', time: '5 phút trước', read: false },
    { id: '2', title: 'Người dùng mới', message: 'Nguyễn Thị Lan đã đăng ký', time: '12 phút trước', read: false },
    { id: '3', title: 'Bình luận chờ duyệt', message: '3 bình luận cần xem xét', time: '30 phút trước', read: false },
    { id: '4', title: 'Cập nhật hệ thống', message: 'Phiên bản 1.2.0 đã sẵn sàng', time: '2 giờ trước', read: true },
    { id: '5', title: 'Báo cáo tuần', message: 'Báo cáo doanh thu tuần 24', time: '1 ngày trước', read: true },
  ];
}

function generateMessagesData() {
  return [
    { id: '1', from: 'Trần Văn Minh', message: 'Xin hỏi về gói Enterprise...', time: '10 phút trước', read: false },
    { id: '2', from: 'Nguyễn Thị Lan', message: 'Cần hỗ trợ reset API key', time: '25 phút trước', read: false },
    { id: '3', from: 'Lê Hoàng An', message: 'Cảm ơn đội ngũ hỗ trợ!', time: '1 giờ trước', read: true },
  ];
}

function generateRolesData() {
  return [
    { id: '1', name: 'Super Admin', description: 'Toàn quyền hệ thống', users: 2, permissions: 48, createdAt: '2025-01-01' },
    { id: '2', name: 'Admin', description: 'Quản trị nội dung và người dùng', users: 5, permissions: 32, createdAt: '2025-01-01' },
    { id: '3', name: 'Editor', description: 'Quản lý bài viết và danh mục', users: 8, permissions: 16, createdAt: '2025-01-01' },
    { id: '4', name: 'Support', description: 'Hỗ trợ khách hàng', users: 12, permissions: 8, createdAt: '2025-01-01' },
    { id: '5', name: 'User', description: 'Người dùng thông thường', users: 12820, permissions: 4, createdAt: '2025-01-01' },
  ];
}

// ======================
// Dashboard snapshot data (stats + charts + activities)
// Generated so they are consistent with the rest of the seed and can be richer
// ======================

function generateDashboardStatsData(usrs: any[], reports: any) {
  const totalUsers = usrs.length;
  const newUsers = Math.floor(totalUsers * 0.03); // ~3%
  const yearlyRevenue = reports?.revenue?.yearlyRevenue ?? 248500000;
  const monthlyRevenue = reports?.revenue?.monthlyRevenue ?? Math.floor(yearlyRevenue / 12);

  return [
    {
      title: 'Tổng người dùng',
      value: totalUsers.toLocaleString('vi-VN'),
      change: 12.5,
      trend: [40, 55, 45, 60, 52, 68, 72],
      icon: 'users' as const,
    },
    {
      title: 'Người dùng mới',
      value: newUsers.toLocaleString('vi-VN'),
      change: 8.2,
      trend: [20, 25, 30, 28, 35, 38, 42],
      icon: 'user-plus' as const,
    },
    {
      title: 'Tổng doanh thu',
      value: `₫${(yearlyRevenue / 1_000_000).toFixed(1)}M`,
      change: reports?.revenue?.changeYearly ?? 15.3,
      trend: [30, 45, 40, 55, 50, 65, 70],
      icon: 'revenue' as const,
    },
    {
      title: 'Đơn hàng',
      value: '1,284',
      change: -2.4,
      trend: [50, 48, 52, 45, 50, 47, 49],
      icon: 'orders' as const,
    },
    {
      title: 'Lượt truy cập',
      value: (reports?.traffic?.visits ?? 89432).toLocaleString('vi-VN'),
      change: reports?.traffic?.changeVisits ?? 22.1,
      trend: [60, 65, 70, 75, 80, 85, 90],
      icon: 'traffic' as const,
    },
    {
      title: 'Bài viết',
      value: '256',
      change: 5.7,
      trend: [10, 12, 15, 14, 18, 20, 22],
      icon: 'articles' as const,
    },
  ];
}

function generateRevenueChartData() {
  // 12 months, realistic growth
  const base = 18000000;
  return Array.from({ length: 12 }, (_, i) => ({
    month: ['T1','T2','T3','T4','T5','T6','T7','T8','T9','T10','T11','T12'][i],
    revenue: Math.floor(base * (1 + i * 0.018) + faker.number.int({ min: -2000000, max: 3000000 })),
    orders: 120 + Math.floor(i * 14) + faker.number.int({ min: -5, max: 15 }),
  }));
}

function generateUserGrowthData(totalUsers: number) {
  const start = Math.floor(totalUsers * 0.64);
  return Array.from({ length: 12 }, (_, i) => {
    const users = Math.floor(start + (totalUsers - start) * (i / 11));
    return {
      month: ['T1','T2','T3','T4','T5','T6','T7','T8','T9','T10','T11','T12'][i],
      users,
      active: Math.floor(users * 0.75),
    };
  });
}

function generateTrafficSourceData() {
  return [
    { name: 'Organic', value: 35, color: '#7a5af8' },
    { name: 'Direct', value: 25, color: '#6938ef' },
    { name: 'Social', value: 20, color: '#9b8afb' },
    { name: 'Referral', value: 12, color: '#bdb4fe' },
    { name: 'Email', value: 8, color: '#d9d6fe' },
  ];
}

function generateDeviceData() {
  return [
    { name: 'Desktop', value: 52, color: '#7a5af8' },
    { name: 'Mobile', value: 38, color: '#6938ef' },
    { name: 'Tablet', value: 10, color: '#9b8afb' },
  ];
}

function generateConversionData(visits: number) {
  return [
    { stage: 'Truy cập', value: visits },
    { stage: 'Đăng ký', value: Math.floor(visits * 0.043) },
    { stage: 'Dùng thử', value: Math.floor(visits * 0.0215) },
    { stage: 'Thanh toán', value: Math.floor(visits * 0.0086) },
    { stage: 'Gia hạn', value: Math.floor(visits * 0.0057) },
  ];
}

function generateRecentActivitiesData() {
  return [
    {
      id: '1',
      type: 'user',
      message: 'Nguyễn Thị Lan đã đăng ký tài khoản mới',
      time: '5 phút trước',
    },
    {
      id: '2',
      type: 'order',
      message: 'Đơn hàng #ORD-2847 đã được thanh toán',
      time: '12 phút trước',
    },
    {
      id: '3',
      type: 'comment',
      message: 'Bình luận mới trên bài "Hướng dẫn AI"',
      time: '25 phút trước',
    },
    {
      id: '4',
      type: 'admin',
      message: 'Admin cập nhật cài đặt SEO website',
      time: '1 giờ trước',
    },
    {
      id: '5',
      type: 'user',
      message: 'Trần Văn Minh nâng cấp gói Pro',
      time: '2 giờ trước',
    },
  ];
}

function generateAllJsonData() {
  const cats = generateCategoriesData();
  const usrs = generateUsersData();
  const arts = generateArticlesData(cats);
  const cmts = generateCommentsData(arts);
  const ords = generateOrdersData();
  const bnrs = generateBannersData();
  const jbs = generateJobsData();
  const custs = generateCustomersData(usrs);
  const invoices = generateInvoicesData();
  const apiKeys = generateApiKeysData();
  const aiTools = generateAiToolsData();
  const aiHistory = generateAiHistoryData(usrs);
  const reports = generateReportData();
  const notifs = generateNotificationsData();
  const msgs = generateMessagesData();
  const roles = generateRolesData();

  const dashboardStatsData = generateDashboardStatsData(usrs, reports);
  const revenueChart = generateRevenueChartData();
  const userGrowth = generateUserGrowthData(usrs.length);
  const trafficSource = generateTrafficSourceData();
  const device = generateDeviceData();
  const conversion = generateConversionData(reports?.traffic?.visits ?? 89432);
  const recentActivitiesData = generateRecentActivitiesData();

  return {
    categories: cats,
    users: usrs,
    articles: arts,
    comments: cmts,
    orders: ords,
    banners: bnrs,
    jobs: jbs,
    customers: custs,
    invoices,
    'api-keys': apiKeys,
    'ai-tools': aiTools,
    'ai-history': aiHistory,
    reports,
    notifications: notifs,
    messages: msgs,
    roles,
    'dashboard-stats': dashboardStatsData,
    'revenue-chart': revenueChart,
    'user-growth': userGrowth,
    'traffic-source': trafficSource,
    'device-data': device,
    'conversion-data': conversion,
    'recent-activities': recentActivitiesData,
  };
}

// ======================
// DB SEED (existing logic)
// ======================

async function hasData(table: any, label: string): Promise<boolean> {
  const result = await db.select({ c: count() }).from(table);
  const total = result[0]?.c ?? 0;
  if (total > 0) {
    console.log(`  ⏭  ${label}: already has ${total} records, skipping.`);
    return true;
  }
  return false;
}

async function seedCategories() {
  console.log('\n📁 Seeding Categories...');
  if (await hasData(categories, 'Categories')) return;

  const data = ARTICLE_CATEGORIES.map((cat, idx) => ({
    name: cat.name,
    slug: cat.slug,
    parent: idx > 3 && Math.random() > 0.7 ? pickRandom(ARTICLE_CATEGORIES.slice(0, 4)).name : null,
    status: Math.random() > 0.85 ? 'inactive' : 'active',
  }));

  await db.insert(categories).values(data);
  console.log(`  ✓ Inserted ${data.length} categories`);
}

async function seedUsers() {
  console.log('\n👥 Seeding Users...');
  if (await hasData(users, 'Users')) return;

  const data = Array.from({ length: NUM_USERS }).map(() => {
    const name = generateVietnameseName();
    const rolePool = ['User', 'User', 'User', 'Pro', 'Pro', 'Admin'];
    const role = pickRandom(rolePool);
    const status = pickRandom([...USER_STATUSES]);

    return {
      name,
      email: generateEmail(name),
      avatar: generateImageUrl(`user-${name}`, 128, 128),
      role,
      status,
      createdAt: faker.date.past({ years: 1.5 }), // fine for DB path
    };
  });

  // Ensure at least one admin + known demo users
  data[0].name = 'Nguyễn Thị Lan';
  data[0].email = 'lan.nguyen@vn168.vn';
  data[0].role = 'Admin';
  data[0].status = 'active';

  data[1].name = 'Trần Văn Minh';
  data[1].email = 'minh.tran@vn168.vn';
  data[1].role = 'Pro';
  data[1].status = 'active';

  await db.insert(users).values(data);
  console.log(`  ✓ Inserted ${data.length} users`);
}

async function seedArticles() {
  console.log('\n📰 Seeding Articles...');
  if (await hasData(articles, 'Articles')) return;

  const allCategories = await db.select().from(categories);
  if (allCategories.length === 0) {
    console.log('  ⚠️  No categories found. Run categories seed first.');
    return;
  }

  const authors = ['Admin AIStarterKit', 'Nguyễn Thị Lan', 'Trần Văn Minh', 'Phạm Thu Hà', 'Lê Hoàng An'];

  const data = Array.from({ length: NUM_ARTICLES }).map((_, i) => {
    const cat = pickRandom(allCategories);
    const title = i < ARTICLE_TITLES.length ? ARTICLE_TITLES[i] : faker.lorem.sentence({ min: 8, max: 14 });
    const slugBase = title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 80);
    const slug = `${slugBase}-${1000 + i}`;

    const status = pickRandom([...ARTICLE_STATUSES]);
    const views = faker.number.int({ min: 80, max: 12400 });
    const featured = Math.random() > 0.75;

    return {
      title,
      slug,
      excerpt: pickRandom([
        'Khám phá cách tận dụng AI để tăng năng suất làm việc và sáng tạo nội dung chuyên nghiệp.',
        'Các chiến lược thực tế giúp sử dụng AI hiệu quả trong quy trình làm việc hàng ngày.',
        faker.lorem.paragraph({ min: 1, max: 2 }).slice(0, 180),
      ]),
      content: `<p>${faker.lorem.paragraphs(4, '<br/><br/>')}</p>`,
      categoryId: cat.id,
      author: pickRandom(authors),
      status,
      views,
      likes: faker.number.int({ min: 5, max: 420 }),
      readTime: faker.number.int({ min: 4, max: 14 }),
      featured,
      coverImage: generateImageUrl(`article-${slugBase}`, 1200, 630),
      publishedAt: status === 'published' ? faker.date.recent({ days: 90 }) : null,
      createdAt: faker.date.past({ years: 1 }),
    };
  });

  await db.insert(articles).values(data);
  console.log(`  ✓ Inserted ${data.length} articles`);
}

async function seedComments() {
  console.log('\n💬 Seeding Comments...');
  if (await hasData(comments, 'Comments')) return;

  const allArticles = await db.select().from(articles);
  if (allArticles.length === 0) {
    console.log('  ⚠️  No articles. Skipping comments.');
    return;
  }

  const data: any[] = [];

  for (let i = 0; i < NUM_COMMENTS; i++) {
    const article = pickRandom(allArticles);
    const name = generateVietnameseName();
    const statuses = ['approved', 'approved', 'approved', 'pending', 'hidden', 'reported'];

    data.push({
      articleId: article.id,
      authorName: name,
      authorAvatar: generateImageUrl(`comment-${name}`, 64, 64),
      content: faker.lorem.sentence({ min: 6, max: 18 }),
      status: pickRandom(statuses),
      likes: faker.number.int({ min: 0, max: 28 }),
      createdAt: faker.date.recent({ days: 45 }),
    });
  }

  await db.insert(comments).values(data);
  console.log(`  ✓ Inserted ${data.length} comments`);
}

async function seedOrders() {
  console.log('\n🧾 Seeding Orders...');
  if (await hasData(orders, 'Orders')) return;

  const data = Array.from({ length: NUM_ORDERS }).map((_, i) => {
    const pkg = pickRandom(PACKAGES);
    const name = generateVietnameseName();
    const email = generateEmail(name);
    const status = pickRandom([...ORDER_STATUSES]);

    const orderNumber = `ORD-${2800 + i}`;

    return {
      orderNumber,
      customerName: name,
      customerEmail: email,
      packageName: pkg.name,
      amount: generateOrderAmount(pkg.price),
      status,
      createdAt: faker.date.recent({ days: 120 }),
    };
  });

  await db.insert(orders).values(data);
  console.log(`  ✓ Inserted ${data.length} orders`);
}

async function seedInvoices() {
  console.log('\n💳 Seeding Invoices...');
  if (await hasData(invoices, 'Invoices')) return;

  const data = Array.from({ length: 18 }).map((_, i) => {
    const statusPool: Array<'paid' | 'pending' | 'overdue'> = ['paid', 'paid', 'paid', 'pending', 'overdue'];
    const name = generateVietnameseName();

    return {
      invoiceNumber: `INV-${String(100 + i).padStart(3, '0')}`,
      customerName: name,
      amount: generateInvoiceAmount(),
      status: pickRandom(statusPool),
      date: faker.date.recent({ days: 40 }),
    };
  });

  await db.insert(invoices).values(data);
  console.log(`  ✓ Inserted ${data.length} invoices`);
}

async function seedBanners() {
  console.log('\n🖼️  Seeding Banners...');
  if (await hasData(banners, 'Banners')) return;

  const positions = [
    'Trang chủ - Hero',
    'Sidebar',
    'Trang Pricing',
    'Trang Blog',
    'Dashboard Header',
  ];

  const data = Array.from({ length: NUM_BANNERS }).map((_, i) => {
    const status: 'active' | 'inactive' | 'scheduled' =
      i === 0 ? 'active' : (Math.random() > 0.3 ? 'active' : 'scheduled');

    return {
      title: pickRandom([
        'Hero Banner - Ưu đãi mùa hè',
        'Sidebar Promo AI Pro',
        'Pricing Campaign Q3',
        'Blog Feature - AI mới',
        'Khám phá công cụ mới',
      ]),
      position: positions[i] || positions[0],
      image: generateImageUrl(`banner-${i}`, 1400, 600),
      status,
      startDate: faker.date.past({ years: 0.3 }),
      endDate: faker.date.future({ years: 0.6 }),
    };
  });

  await db.insert(banners).values(data);
  console.log(`  ✓ Inserted ${data.length} banners`);
}

async function seedJobs() {
  console.log('\n💼 Seeding Jobs...');
  if (await hasData(jobs, 'Jobs')) return;

  const data = Array.from({ length: NUM_JOBS }).map((_, i) => {
    const title = i < 4 ? pickRandom([
      'Senior Frontend Developer (React/Next.js)',
      'AI/ML Engineer',
      'Product Designer (AI SaaS)',
      'Backend Engineer - Platform',
    ]) : faker.person.jobTitle() + ' (AI)';

    const slug = title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-');

    const dept = pickRandom(['engineering', 'product', 'marketing', 'design', 'hr'] as const);

    return {
      slug: `${slug}-${900 + i}`,
      title,
      excerpt: 'Tham gia phát triển nền tảng AI SaaS với stack hiện đại tại TP.HCM.',
      department: dept,
      location: pickRandom(['TP. Hồ Chí Minh', 'Hà Nội', 'Remote', 'Hybrid - TP.HCM']),
      jobType: pickRandom(['full-time', 'part-time', 'remote'] as const),
      level: pickRandom(['junior', 'mid', 'senior', 'lead'] as const),
      salaryMin: 22000000,
      salaryMax: 62000000,
      salaryCurrency: 'VND',
      experience: pickRandom(['1-2 năm', '2-3 năm', '3-5 năm', '5+ năm']),
      headcount: pickRandom([1, 2, 3]),
      publishedAt: faker.date.recent({ days: 60 }),
      deadline: faker.date.future({ years: 0.4 }),
      views: faker.number.int({ min: 240, max: 5200 }),
      likes: faker.number.int({ min: 12, max: 180 }),
      featured: i === 0,
      companyLogo: '/images/black.png',
      coverImage: generateImageUrl(`job-${slug}`, 1200, 500),
      skills: JSON.stringify(['TypeScript', 'React', 'Next.js', 'AI', 'Tailwind']),
      description: 'Chúng tôi đang tìm kiếm thành viên tài năng để xây dựng các sản phẩm AI chất lượng cao.',
      responsibilities: JSON.stringify(['Xây dựng tính năng mới', 'Review code', 'Hợp tác với team design']),
      requirements: JSON.stringify(['Kinh nghiệm 3+ năm', 'Thành thạo React/TS', 'Tư duy sản phẩm tốt']),
      benefits: JSON.stringify(['Lương thưởng cạnh tranh', 'BHYT cao cấp', 'Làm việc linh hoạt']),
    };
  });

  await db.insert(jobs).values(data);
  console.log(`  ✓ Inserted ${data.length} jobs`);
}

export async function seedAll() {
  if (SEED_TO_DB) {
    // Order matters for foreign keys
    await seedCategories();
    await seedUsers();
    await seedArticles();
    await seedComments();
    await seedOrders();
    await seedInvoices();
    await seedBanners();
    await seedJobs();
  } else {
    console.log('  ⏭  SEED_TO_DB=false → Skipping database insert');
  }

  // ======================
  // JSON generation (when SEED_TO_JSON is enabled)
  // Especially useful for local development
  // ======================
  if (SEED_TO_JSON) {
    console.log('\n📦 Generating JSON seed files (local/dev mode)...');
    const jsonData = generateAllJsonData();
    writeSeedJson(jsonData);
    console.log('  ✓ JSON seed data generated successfully.');
  } else {
    console.log('  ⏭  SEED_TO_JSON not enabled (set SEED_TO_JSON=true to generate JSON files)');
  }
}

async function main() {
  console.log('🌱 Starting VN168 Random Data Seeder...');
  console.log('   Locale: vi | Reproducible seed: 20260630');

  try {
    await seedAll();

    console.log('\n✅ Seed completed successfully!');

    if (SEED_TO_JSON) {
      console.log('   → JSON files are available in ./seed-data/ (great for local mocks or fixtures)');
    }
    if (SEED_TO_DB) {
      console.log('   → Data has been inserted into the database.');
    }
  } catch (error) {
    console.error('\n❌ Seed failed:');
    console.error(error);
    process.exit(1);
  } finally {
    process.exit(0);
  }
}

if (require.main === module) {
  main();
}
